/* 
 * Megaputer Text Mining API
 *
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using TmApi.Client;
using TmApi.Model;

namespace TmApi.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IServerApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Change password
        /// </summary>
        /// <remarks>
        /// Use this request to change the password.
        /// </remarks>
        /// <exception cref="TmApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changePasswordRequest">Change password request</param>
        /// <returns></returns>
        void ChangePassword (ChangePasswordRequest changePasswordRequest);

        /// <summary>
        /// Change password
        /// </summary>
        /// <remarks>
        /// Use this request to change the password.
        /// </remarks>
        /// <exception cref="TmApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changePasswordRequest">Change password request</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ChangePasswordWithHttpInfo (ChangePasswordRequest changePasswordRequest);
        /// <summary>
        /// Server information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TmApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ServerInfo</returns>
        ServerInfo GetServerInfo ();

        /// <summary>
        /// Server information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TmApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ServerInfo</returns>
        ApiResponse<ServerInfo> GetServerInfoWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Change password
        /// </summary>
        /// <remarks>
        /// Use this request to change the password.
        /// </remarks>
        /// <exception cref="TmApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changePasswordRequest">Change password request</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ChangePasswordAsync (ChangePasswordRequest changePasswordRequest);

        /// <summary>
        /// Change password
        /// </summary>
        /// <remarks>
        /// Use this request to change the password.
        /// </remarks>
        /// <exception cref="TmApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changePasswordRequest">Change password request</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ChangePasswordAsyncWithHttpInfo (ChangePasswordRequest changePasswordRequest);
        /// <summary>
        /// Server information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TmApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ServerInfo</returns>
        System.Threading.Tasks.Task<ServerInfo> GetServerInfoAsync ();

        /// <summary>
        /// Server information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TmApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ServerInfo)</returns>
        System.Threading.Tasks.Task<ApiResponse<ServerInfo>> GetServerInfoAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ServerApi : IServerApi
    {
        private TmApi.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ServerApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ServerApi(String basePath)
        {
            this.Configuration = new TmApi.Client.Configuration { BasePath = basePath };

            ExceptionFactory = TmApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ServerApi"/> class
        /// </summary>
        /// <returns></returns>
        public ServerApi()
        {
            this.Configuration = TmApi.Client.Configuration.Default;

            ExceptionFactory = TmApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ServerApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ServerApi(TmApi.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = TmApi.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = TmApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public TmApi.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public TmApi.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Change password Use this request to change the password.
        /// </summary>
        /// <exception cref="TmApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changePasswordRequest">Change password request</param>
        /// <returns></returns>
        public void ChangePassword (ChangePasswordRequest changePasswordRequest)
        {
             ChangePasswordWithHttpInfo(changePasswordRequest);
        }

        /// <summary>
        /// Change password Use this request to change the password.
        /// </summary>
        /// <exception cref="TmApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changePasswordRequest">Change password request</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> ChangePasswordWithHttpInfo (ChangePasswordRequest changePasswordRequest)
        {
            // verify the required parameter 'changePasswordRequest' is set
            if (changePasswordRequest == null)
                throw new ApiException(400, "Missing required parameter 'changePasswordRequest' when calling ServerApi->ChangePassword");

            var localVarPath = "/change-password";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (changePasswordRequest != null && changePasswordRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(changePasswordRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = changePasswordRequest; // byte array
            }

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ChangePassword", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Change password Use this request to change the password.
        /// </summary>
        /// <exception cref="TmApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changePasswordRequest">Change password request</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ChangePasswordAsync (ChangePasswordRequest changePasswordRequest)
        {
             await ChangePasswordAsyncWithHttpInfo(changePasswordRequest);

        }

        /// <summary>
        /// Change password Use this request to change the password.
        /// </summary>
        /// <exception cref="TmApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changePasswordRequest">Change password request</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ChangePasswordAsyncWithHttpInfo (ChangePasswordRequest changePasswordRequest)
        {
            // verify the required parameter 'changePasswordRequest' is set
            if (changePasswordRequest == null)
                throw new ApiException(400, "Missing required parameter 'changePasswordRequest' when calling ServerApi->ChangePassword");

            var localVarPath = "/change-password";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (changePasswordRequest != null && changePasswordRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(changePasswordRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = changePasswordRequest; // byte array
            }

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ChangePassword", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Server information 
        /// </summary>
        /// <exception cref="TmApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ServerInfo</returns>
        public ServerInfo GetServerInfo ()
        {
             ApiResponse<ServerInfo> localVarResponse = GetServerInfoWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Server information 
        /// </summary>
        /// <exception cref="TmApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ServerInfo</returns>
        public ApiResponse< ServerInfo > GetServerInfoWithHttpInfo ()
        {

            var localVarPath = "/server";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (BasicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetServerInfo", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ServerInfo>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ServerInfo) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ServerInfo)));
        }

        /// <summary>
        /// Server information 
        /// </summary>
        /// <exception cref="TmApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ServerInfo</returns>
        public async System.Threading.Tasks.Task<ServerInfo> GetServerInfoAsync ()
        {
             ApiResponse<ServerInfo> localVarResponse = await GetServerInfoAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Server information 
        /// </summary>
        /// <exception cref="TmApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ServerInfo)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ServerInfo>> GetServerInfoAsyncWithHttpInfo ()
        {

            var localVarPath = "/server";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (BasicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetServerInfo", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ServerInfo>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ServerInfo) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ServerInfo)));
        }

    }
}
