/* 
 * Megaputer Text Mining API
 *
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TmApi.Client.OpenAPIDateConverter;

namespace TmApi.Model
{
    /// <summary>
    /// EntitiesResponseEntities
    /// </summary>
    [DataContract]
    public partial class EntitiesResponseEntities :  IEquatable<EntitiesResponseEntities>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EntitiesResponseEntities" /> class.
        /// </summary>
        /// <param name="type">Entity type.</param>
        /// <param name="attributes">Entity attributes. Depends on entity type.</param>
        /// <param name="positions">Entity positions in text.</param>
        public EntitiesResponseEntities(string type = default(string), Dictionary<string, Object> attributes = default(Dictionary<string, Object>), List<EntitiesResponsePositions> positions = default(List<EntitiesResponsePositions>))
        {
            this.Type = type;
            this.Attributes = attributes;
            this.Positions = positions;
        }
        
        /// <summary>
        /// Entity type
        /// </summary>
        /// <value>Entity type</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Entity attributes. Depends on entity type
        /// </summary>
        /// <value>Entity attributes. Depends on entity type</value>
        [DataMember(Name="attributes", EmitDefaultValue=false)]
        public Dictionary<string, Object> Attributes { get; set; }

        /// <summary>
        /// Entity positions in text
        /// </summary>
        /// <value>Entity positions in text</value>
        [DataMember(Name="positions", EmitDefaultValue=false)]
        public List<EntitiesResponsePositions> Positions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EntitiesResponseEntities {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  Positions: ").Append(Positions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EntitiesResponseEntities);
        }

        /// <summary>
        /// Returns true if EntitiesResponseEntities instances are equal
        /// </summary>
        /// <param name="input">Instance of EntitiesResponseEntities to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EntitiesResponseEntities input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Attributes == input.Attributes ||
                    this.Attributes != null &&
                    this.Attributes.SequenceEqual(input.Attributes)
                ) && 
                (
                    this.Positions == input.Positions ||
                    this.Positions != null &&
                    this.Positions.SequenceEqual(input.Positions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Attributes != null)
                    hashCode = hashCode * 59 + this.Attributes.GetHashCode();
                if (this.Positions != null)
                    hashCode = hashCode * 59 + this.Positions.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
