/* 
 * Megaputer Text Mining API
 *
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TmApi.Client.OpenAPIDateConverter;

namespace TmApi.Model
{
    /// <summary>
    /// TokensResponseDocuments
    /// </summary>
    [DataContract]
    public partial class TokensResponseDocuments :  IEquatable<TokensResponseDocuments>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TokensResponseDocuments" /> class.
        /// </summary>
        /// <param name="id">Index of document in input documents array.</param>
        /// <param name="sentences">List of sentences.</param>
        public TokensResponseDocuments(int? id = default(int?), List<TokensResponseSentences> sentences = default(List<TokensResponseSentences>))
        {
            this.Id = id;
            this.Sentences = sentences;
        }
        
        /// <summary>
        /// Index of document in input documents array
        /// </summary>
        /// <value>Index of document in input documents array</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// List of sentences
        /// </summary>
        /// <value>List of sentences</value>
        [DataMember(Name="sentences", EmitDefaultValue=false)]
        public List<TokensResponseSentences> Sentences { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TokensResponseDocuments {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Sentences: ").Append(Sentences).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TokensResponseDocuments);
        }

        /// <summary>
        /// Returns true if TokensResponseDocuments instances are equal
        /// </summary>
        /// <param name="input">Instance of TokensResponseDocuments to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TokensResponseDocuments input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Sentences == input.Sentences ||
                    this.Sentences != null &&
                    this.Sentences.SequenceEqual(input.Sentences)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Sentences != null)
                    hashCode = hashCode * 59 + this.Sentences.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
