/* 
 * Megaputer Text Mining API
 *
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TmApi.Client.OpenAPIDateConverter;

namespace TmApi.Model
{
    /// <summary>
    /// TotalLimitPeriodic1Response
    /// </summary>
    [DataContract]
    public partial class TotalLimitPeriodic1Response :  IEquatable<TotalLimitPeriodic1Response>, IValidatableObject
    {
        /// <summary>
        /// A period when limitations apply
        /// </summary>
        /// <value>A period when limitations apply</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum NTUPeriod1Enum
        {
            /// <summary>
            /// Enum Second for value: Second
            /// </summary>
            [EnumMember(Value = "Second")]
            Second = 1,

            /// <summary>
            /// Enum Minute for value: Minute
            /// </summary>
            [EnumMember(Value = "Minute")]
            Minute = 2,

            /// <summary>
            /// Enum Hour for value: Hour
            /// </summary>
            [EnumMember(Value = "Hour")]
            Hour = 3,

            /// <summary>
            /// Enum Day for value: Day
            /// </summary>
            [EnumMember(Value = "Day")]
            Day = 4,

            /// <summary>
            /// Enum Month for value: Month
            /// </summary>
            [EnumMember(Value = "Month")]
            Month = 5

        }

        /// <summary>
        /// A period when limitations apply
        /// </summary>
        /// <value>A period when limitations apply</value>
        [DataMember(Name="NTUPeriod1", EmitDefaultValue=false)]
        public NTUPeriod1Enum? NTUPeriod1 { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TotalLimitPeriodic1Response" /> class.
        /// </summary>
        /// <param name="nTUPeriod1">A period when limitations apply.</param>
        /// <param name="nTUInPeriod1Limit">A maximum number of requests in the specified period.</param>
        /// <param name="nTUInPeriod1">A number of requests that have already been processed.</param>
        public TotalLimitPeriodic1Response(NTUPeriod1Enum? nTUPeriod1 = default(NTUPeriod1Enum?), int? nTUInPeriod1Limit = default(int?), int? nTUInPeriod1 = default(int?))
        {
            this.NTUPeriod1 = nTUPeriod1;
            this.NTUInPeriod1Limit = nTUInPeriod1Limit;
            this.NTUInPeriod1 = nTUInPeriod1;
        }
        

        /// <summary>
        /// A maximum number of requests in the specified period
        /// </summary>
        /// <value>A maximum number of requests in the specified period</value>
        [DataMember(Name="NTUInPeriod1Limit", EmitDefaultValue=false)]
        public int? NTUInPeriod1Limit { get; set; }

        /// <summary>
        /// A number of requests that have already been processed
        /// </summary>
        /// <value>A number of requests that have already been processed</value>
        [DataMember(Name="NTUInPeriod1", EmitDefaultValue=false)]
        public int? NTUInPeriod1 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TotalLimitPeriodic1Response {\n");
            sb.Append("  NTUPeriod1: ").Append(NTUPeriod1).Append("\n");
            sb.Append("  NTUInPeriod1Limit: ").Append(NTUInPeriod1Limit).Append("\n");
            sb.Append("  NTUInPeriod1: ").Append(NTUInPeriod1).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TotalLimitPeriodic1Response);
        }

        /// <summary>
        /// Returns true if TotalLimitPeriodic1Response instances are equal
        /// </summary>
        /// <param name="input">Instance of TotalLimitPeriodic1Response to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TotalLimitPeriodic1Response input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.NTUPeriod1 == input.NTUPeriod1 ||
                    (this.NTUPeriod1 != null &&
                    this.NTUPeriod1.Equals(input.NTUPeriod1))
                ) && 
                (
                    this.NTUInPeriod1Limit == input.NTUInPeriod1Limit ||
                    (this.NTUInPeriod1Limit != null &&
                    this.NTUInPeriod1Limit.Equals(input.NTUInPeriod1Limit))
                ) && 
                (
                    this.NTUInPeriod1 == input.NTUInPeriod1 ||
                    (this.NTUInPeriod1 != null &&
                    this.NTUInPeriod1.Equals(input.NTUInPeriod1))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NTUPeriod1 != null)
                    hashCode = hashCode * 59 + this.NTUPeriod1.GetHashCode();
                if (this.NTUInPeriod1Limit != null)
                    hashCode = hashCode * 59 + this.NTUInPeriod1Limit.GetHashCode();
                if (this.NTUInPeriod1 != null)
                    hashCode = hashCode * 59 + this.NTUInPeriod1.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
