/* 
 * Megaputer Text Mining API
 *
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TmApi.Client.OpenAPIDateConverter;
using static TmApi.Model.TotalLimitPeriodic1Response;
using static TmApi.Model.TotalLimitPeriodic2Response;

namespace TmApi.Model
{
    /// <summary>
    /// TotalLimitResponse
    /// </summary>
    [DataContract]
    public partial class TotalLimitResponse :  IEquatable<TotalLimitResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TotalLimitResponse" /> class.
        /// </summary>
        public TotalLimitResponse(int? nTULimit = default(int?), int? nTU = default(int?), NTUPeriod1Enum? nTUPeriod1 = default(NTUPeriod1Enum?), int? nTUInPeriod1Limit = default(int?), int? nTUInPeriod1 = default(int?), NTUPeriod2Enum? nTUPeriod2 = default(NTUPeriod2Enum?), int? nTUInPeriod2Limit = default(int?), int? nTUInPeriod2 = default(int?))
        {
        }
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TotalLimitResponse {\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TotalLimitResponse);
        }

        /// <summary>
        /// Returns true if TotalLimitResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TotalLimitResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TotalLimitResponse input)
        {
            if (input == null)
                return false;

            return false;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
